"""Recreate manuscript figures with the same TeX fonts and physical dimensions.

Both vector formats use Matplotlib's PGF backend and pdflatex. The PNG previews
are rendered from the resulting PDFs, so they show the same typography.
The manuscript should load pgf, amsmath, and amssymb, and input the PGF files
without resizing. All figures are exactly the AISTATS text width, 6.75 inches.
Scientific results and uncertainty calculations are unchanged.
"""
from pathlib import Path
import argparse
import json
import subprocess
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('pgf')
import matplotlib.pyplot as plt
from matplotlib.ticker import FixedLocator, NullFormatter

from settings import RESULTS as RES, FIGURES as FIG, CONFIG, MODE
BOOTSTRAP_REPS=CONFIG['bootstrap_replications']
WIDTH_IN=6.75
TEX_PREAMBLE=r'\usepackage{amsmath,amssymb}'
# The manuscript uses 10 pt Computer Modern body text and 9 pt small text.
# pgf.rcfonts=False leaves the TeX fonts unchanged by Matplotlib font discovery.
STYLE={
    'pgf.texsystem':'pdflatex',
    'pgf.rcfonts':False,
    'pgf.preamble':TEX_PREAMBLE,
    'text.usetex':True,
    'font.family':'serif',
    'font.serif':['Computer Modern Roman'],
    'mathtext.fontset':'cm',
    'font.size':9,
    'axes.titlesize':10,
    'axes.labelsize':10,
    'legend.fontsize':9,
    'xtick.labelsize':9,
    'ytick.labelsize':9,
    'axes.spines.top':False,
    'axes.spines.right':False,
    'axes.linewidth':.7,
    'axes.titlepad':5,
    'axes.labelpad':3,
    'xtick.major.pad':3,
    'ytick.major.pad':3,
    'legend.frameon':False,
    'legend.handlelength':1.5,
    'legend.handletextpad':.45,
    'legend.columnspacing':1.35,
    'legend.labelspacing':.3,
    'legend.borderaxespad':0,
    'savefig.bbox':None,
    'savefig.pad_inches':0,
}
plt.rcParams.update(STYLE)
COLORS=['#136f91','#c64b33','#4b8b45','#8b5e9c']
LAYOUT={}


def export(fig,stem,legends=()):
    """Write uncropped PGF/PDF files and derive the preview from that PDF."""
    if abs(fig.get_figwidth()-WIDTH_IN)>1e-12:
        raise ValueError('Figure width must equal the manuscript text width')
    fig.canvas.draw()
    renderer=fig.canvas.get_renderer()
    # Record physical bounds so legend alignment can be checked independently.
    axes_bounds=[list(ax.get_position().bounds) for ax in fig.axes]
    tight_bounds=[list(ax.get_tightbbox(renderer).transformed(fig.transFigure.inverted()).bounds) for ax in fig.axes]
    legend_bounds=[list(legend.get_window_extent(renderer).transformed(fig.transFigure.inverted()).bounds) for legend in legends]
    for box in legend_bounds+tight_bounds:
        x,y,w,h=box
        if min(x,y)<-1e-6 or x+w>1+1e-6 or y+h>1+1e-6:
            raise RuntimeError(f'Figure text extends beyond the canvas: {box}')
    fig.savefig(FIG/f'{stem}.pgf',bbox_inches=None)
    fig.savefig(FIG/f'{stem}.pdf',bbox_inches=None)
    subprocess.run(['pdftoppm','-singlefile','-png','-r','180',str(FIG/f'{stem}.pdf'),str(FIG/stem)],check=True)
    LAYOUT[stem]={'width_inches':fig.get_figwidth(),'height_inches':fig.get_figheight(),'axes_bounds_figure_fraction':axes_bounds,'axes_tight_bounds_figure_fraction':tight_bounds,'legend_bounds_figure_fraction':legend_bounds}
    plt.close(fig)


def efficiency_intervals(spectrum,summary):
    """Same paired bootstrap as the archived figure, with no result-table writes."""
    order=['MOM','PH(0.25)','PH(1)','PH(4)','PH(16)','Mean']
    saved=pd.read_csv(RES/f'efficiency_ratio_{spectrum}.csv').set_index('method').loc[order]
    if MODE=='paper':
        # The compact archive retains paired bootstrap intervals, not all replicates.
        value=summary.mse/summary.loc['Mean','mse']
        np.testing.assert_allclose(value,saved.mse_ratio,rtol=1e-12,atol=1e-14)
        return value,saved.mc_low.to_numpy(),saved.mc_high.to_numpy()
    raw=pd.read_csv(RES/'functional_point_replicates.csv.gz')
    paired=raw[(raw.spectrum==spectrum)&(raw.distribution=='gaussian')&(raw.mechanism=='clean')].pivot(index='replicate',columns='method',values='squared_error')
    rng=np.random.default_rng(20260919)
    idx=rng.integers(len(paired),size=(BOOTSTRAP_REPS,len(paired)))
    denominator=paired['Mean'].to_numpy()[idx].mean(1)
    lower=[]
    upper=[]
    for method in order:
        ratio=paired[method].to_numpy()[idx].mean(1)/denominator
        lo,hi=np.quantile(ratio,[.025,.975])
        lower.append(lo)
        upper.append(hi)
    value=summary.mse/summary.loc['Mean','mse']
    # Reporting never changes simulation artifacts. All modes check the saved
    # paired bootstrap table generated by run_functional (or archived in paper).
    saved=pd.read_csv(RES/f'efficiency_ratio_{spectrum}.csv').set_index('method').loc[order]
    np.testing.assert_allclose(lower,saved.mc_low,rtol=1e-12,atol=1e-14)
    np.testing.assert_allclose(upper,saved.mc_high,rtol=1e-12,atol=1e-14)
    np.testing.assert_allclose(value,saved.mse_ratio,rtol=1e-12,atol=1e-14)
    return value,np.asarray(lower),np.asarray(upper)


def overview():
    scalar=pd.read_csv(RES/'scalar_summary.csv')
    point=pd.read_csv(RES/'functional_point_summary.csv')
    fig,axes=plt.subplots(2,3,figsize=(WIDTH_IN,4.95))
    # A shared top-row legend occupies the gap between the two rows.
    fig.subplots_adjust(left=.085,right=.992,bottom=.12,top=.925,wspace=.59,hspace=1.05)
    # Reserve space for the full HOMER labels while preserving the panel tops
    # and shared legend position. Font sizes and physical canvas are unchanged.
    for ax in axes[1]:
        position=ax.get_position()
        ax.set_position([position.x0,.165,position.width,position.y1-.165])
    metrics=[
        ('plugin_mean_covered','Estimated / mean','o','-',COLORS[1]),
        ('plugin_target_covered','Estimated / target','s','-',COLORS[0]),
        ('oracle_mean_covered','Population / mean','o','--',COLORS[2]),
        ('oracle_target_covered','Population / target','s','--',COLORS[3]),
    ]
    for ax,schedule,title in zip(axes[0],['slow','boundary','many'],['(a) Slow block growth','(b) Boundary schedule','(c) Too many blocks']):
        for metric,label,marker,style,color in metrics:
            q=scalar[(scalar.schedule==schedule)&(scalar.metric==metric)].sort_values('n')
            ax.errorbar(range(3),q.coverage,yerr=[q.coverage-q.mc_low,q.mc_high-q.coverage],label=label,marker=marker,ls=style,color=color,lw=1,ms=3,capsize=1.8)
        ax.axhline(.95,color='.45',lw=.7,ls=':')
        ax.set_xticks(range(3),['4','5','6'])
        ax.set_xlabel(r'$a$, with $n=2^{3a}$')
        ax.set_title(title)
        ax.set_ylim((0,1.01) if MODE=='smoke' else ((.88,.98) if schedule=='slow' else ((.91,.98) if schedule=='boundary' else (.40,1.0))))
    axes[0,0].set_ylabel('Coverage')
    handles,labels=axes[0,0].get_legend_handles_labels()
    upper_center=(axes[0,0].get_position().x0+axes[0,2].get_position().x1)/2
    common=fig.legend(handles,labels,loc='center',bbox_to_anchor=(upper_center,.492),ncol=2)

    order=['MOM','PH(0.25)','PH(1)','PH(4)','PH(16)','Mean']
    ax=axes[1,0]
    for spectrum,color,mark in [('concentrated',COLORS[1],'o'),('diffuse',COLORS[0],'s')]:
        q=point[(point.spectrum==spectrum)&(point.distribution=='gaussian')&(point.mechanism=='clean')].set_index('method').loc[order]
        value,lower,upper=efficiency_intervals(spectrum,q)
        ax.errorbar(range(6),value,yerr=[value-lower,upper-value],marker=mark,ms=3,color=color,label=spectrum,capsize=2,lw=1)
    ax.axhline(1,color='.5',lw=.7,ls=':')
    ax.set_xticks(range(6),['MOM','.25','1','4','16','Mean'],rotation=35,ha='right')
    ax.set_xlabel(r'HOMER threshold $\lambda$')
    ax.set_ylabel('MSE / mean MSE')
    ax.set_title('(d) Gaussian efficiency')
    efficiency_legend=ax.legend(loc='upper right',handlelength=1.0,handletextpad=.3)

    order=['MOM','PH(1)','Adaptive(2)','PH(16)','Mean']
    for ax,mechanism,title in [(axes[1,1],'whole_block','(e) Block contamination'),(axes[1,2],'raw_dispersed','(f) Raw contamination')]:
        for magnitude,color,mark in [(10,COLORS[0],'o'),(100,COLORS[1],'s')]:
            q=point[(point.spectrum=='concentrated')&(point.distribution=='gaussian')&(point.mechanism==mechanism)&(point.magnitude==magnitude)].set_index('method').loc[order]
            ax.errorbar(range(5),q.q95,yerr=[q.q95-q.q95_mc_low,q.q95_mc_high-q.q95],marker=mark,color=color,ms=3,lw=1,capsize=2,label=f'Shift {magnitude}')
        ax.set_xticks(range(5),['MOM','HOMER(1)','Adaptive\nHOMER','HOMER(16)','Mean'],rotation=55,ha='right')
        ax.set_yscale('log')
        ax.set_ylabel('95th-percentile norm error')
        ax.set_title(title)
    axes[1,2].yaxis.set_major_locator(FixedLocator([.5,1.,5.]))
    axes[1,2].set_yticklabels([r'$0.5$',r'$1$',r'$5$'])
    axes[1,2].yaxis.set_minor_formatter(NullFormatter())
    shift_legend=axes[1,1].legend(loc='upper left')
    export(fig,'exp_overview',[common,efficiency_legend,shift_legend])


def functional_and_wearable():
    functional=pd.read_csv(RES/'functional_inference_summary.csv')
    wearable=pd.read_csv(RES/'wearable_results.csv')
    fig,axes=plt.subplots(1,3,figsize=(WIDTH_IN,3.10))
    # All three panels have the same plotting rectangle. The bottom band is
    # reserved for a two-row shared legend and a separate stacked third legend.
    fig.subplots_adjust(left=.077,right=.994,top=.895,bottom=.335,wspace=.47)
    for ax,contrast,title in zip(axes[:2],['interval_average','evening_minus_morning'],['Interval average','Evening minus morning']):
        for spectrum,marker in [('concentrated','o'),('diffuse','s')]:
            for distribution,color,style in [('gaussian',COLORS[0],'-'),('exponential',COLORS[1],'--')]:
                q=functional[(functional.spectrum==spectrum)&(functional.distribution==distribution)&(functional.contrast==contrast)]
                offset=(-.12 if spectrum=='concentrated' else .12)+(-.035 if distribution=='gaussian' else .035)
                ax.errorbar(np.arange(3)+offset,q.coverage,yerr=[q.coverage-q.mc_low,q.mc_high-q.coverage],marker=marker,color=color,ls=style,capsize=2,ms=3,label=f'{spectrum}, {distribution}')
        ax.axhline(.95,color='.4',ls=':',lw=.8)
        ax.set_ylim((0,1.01) if MODE=='smoke' else (.87,.99))
        ax.set_xticks(range(3),['16','32','64'])
        ax.set_xlabel('Number of blocks')
        ax.set_ylabel('Coverage')
        ax.set_title(title)
    handles,labels=axes[0].get_legend_handles_labels()
    # Matplotlib fills columns first. This order places a spectrum in each
    # column and the two distribution laws in separate rows.
    first_two=axes[0].get_position().union([axes[0].get_position(),axes[1].get_position()])
    center12=(first_two.x0+first_two.x1)/2
    shared=fig.legend(handles,labels,loc='center',bbox_to_anchor=(center12,.105),ncol=2,columnspacing=1.15,handlelength=1.35)

    ax=axes[2]
    for method,color,marker in [('Mean',COLORS[2],'^'),('MOM',COLORS[0],'s'),('Adaptive(2)',COLORS[1],'o')]:
        q=wearable[(wearable.mechanism=='one_block')&(wearable.amplitude_multiplier==10)&(wearable.method==method)]
        label='Adaptive HOMER' if method=='Adaptive(2)' else method
        ax.plot(q.activity,q.shift_relative_clean_mean,marker=marker,color=color,label=label,ms=4)
    ax.set_yscale('symlog',linthresh=.01)
    ax.set_ylim(bottom=-.002)
    ax.set_xticks(range(1,7))
    ax.set_xlabel('Activity identifier')
    ax.set_ylabel('Shift / clean subject mean')
    ax.set_title('Energy stress')
    center3=(ax.get_position().x0+ax.get_position().x1)/2
    handles3,labels3=ax.get_legend_handles_labels()
    third=fig.legend(handles3,labels3,loc='center',bbox_to_anchor=(center3,.105),ncol=1)
    export(fig,'exp_functional_wearable',[shared,third])
    LAYOUT['exp_functional_wearable']['shared_legend_center_x']=center12
    LAYOUT['exp_functional_wearable']['third_legend_center_x']=center3


def covariance_illustration():
    """Prespecified replicate zero, with one unclipped scale for all matrices."""
    saved=np.load(RES/('covariance_display.npz' if MODE=='paper' else 'covariance_estimates.npz'),allow_pickle=False)
    replication=int(saved['display_replicate'])
    delta=float(saved['display_delta'])
    scenario=int(np.flatnonzero(saved['delta']==delta)[0])
    methods=list(saved['methods'])
    fitted=saved['estimates']
    matrices=[saved['truth'],fitted[replication,0,methods.index('Mean')]]
    matrices.extend(fitted[replication,scenario,methods.index(name)] for name in ['Mean','GMed','Adaptive PH'])
    # Fixing a shared bound from all displayed entries prevents hidden clipping.
    bound=float(np.ceil(4*max(np.abs(a).max() for a in matrices))/4)
    fig,axes=plt.subplots(1,5,figsize=(WIDTH_IN,1.8))
    fig.subplots_adjust(left=.034,right=.993,bottom=.30,top=.84,wspace=.16)
    for number,(ax,matrix,title) in enumerate(zip(axes,matrices,['Truth','Clean mean','Stressed mean','Geometric median','Adaptive HOMER'])):
        mesh=ax.pcolormesh(np.arange(13),np.arange(13),matrix,cmap='RdBu_r',vmin=-bound,vmax=bound,shading='flat',rasterized=False,linewidth=0)
        ax.set_aspect('equal')
        ax.set_xlim(0,12)
        ax.set_ylim(12,0)
        ax.set_xticks([.5,5.5,11.5],['1','6','12'])
        ax.set_yticks([.5,5.5,11.5],['1','6','12'] if number==0 else [])
        ax.tick_params(length=2,pad=2)
        ax.set_title(title,pad=5)
        for spine in ax.spines.values():spine.set_visible(False)
    color_ax=fig.add_axes([.34,.105,.32,.038])
    bar=fig.colorbar(mesh,cax=color_ax,orientation='horizontal',ticks=[-bound,0,bound])
    bar.solids.set_rasterized(False)
    bar.solids.set_edgecolor('face')
    # A tiny same-color overlap prevents PDF viewer seams between vector cells.
    bar.solids.set_linewidth(.3)
    bar.ax.tick_params(length=2,pad=2)
    export(fig,'exp_covariance')
    LAYOUT['exp_covariance'].update(display_replicate=replication,display_delta=delta,shared_color_limits=[-bound,bound],entry_min=float(min(a.min() for a in matrices)),entry_max=float(max(a.max() for a in matrices)),vector_cells=True,selection='replicate zero and delta 32 fixed before execution')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--only-covariance',action='store_true',help='Generate only the covariance illustration')
    parser.add_argument('--study',nargs='+',choices=['all','scalar','functional','wearable','covariance'],default=['all'])
    args=parser.parse_args()
    studies={'covariance'} if args.only_covariance else (set(['scalar','functional','wearable','covariance']) if 'all' in args.study else set(args.study))
    style_path=FIG/'figure_style.json'
    if style_path.exists():LAYOUT.update(json.loads(style_path.read_text())['figures'])
    if {'scalar','functional'}<=studies:
        overview()
    elif 'scalar' in studies:
        print('Overview requires scalar and functional results; no overview was generated.')
    if {'functional','wearable'}<=studies:
        functional_and_wearable()
    elif studies & {'functional','wearable'}:
        print('Combined functional/wearable figure requires both studies; it was not generated.')
    if 'covariance' in studies:
        covariance_illustration()
    (FIG/'figure_style.json').write_text(json.dumps({'mode':MODE,'bootstrap_replications':BOOTSTRAP_REPS,'backend':'pgf','texsystem':'pdflatex','preamble':TEX_PREAMBLE,'font_family':'Computer Modern','font_points':{'body':9,'axis_labels':10,'titles':10,'ticks':9,'legends':9},'canvas_width_inches':WIDTH_IN,'bbox_cropping':False,'preview_source':'pdftoppm rendering of the PGF-backend PDF','figures':LAYOUT},indent=2))

if __name__=='__main__':
    main()
